### PR TITLE
[Xcode 13.3] Fix for artifact not found for target

### LINKED ISSUE #3: Xcode 13.3 cannot resolve the binary target artifact when using Swift Package Manager
When using Xcode 13.3 any project using CertificateSDK through Swift Package Manager encounters an error when trying to resolve packages.  Xcode 13.2.1 and earlier work fine.

See PR #2 for a screenshot and fix.

This has to do with a change in Xcode 13.3 where the the binary target name specified in the `Package.swift` must be the same as the filename of the binary target artifact (minus the path extension).

### PR DESCRIPTION
**Pull request by PinkidG**
# Problem
With the upcoming version of Xcode 13.3 there seems to be a new behaviour for binary targets. It will throw an error (`artifact not found for target `) if the xcframework file name is not identical with the binary target name.

Screenshot 2022-03-10 at 11 24 07

## Proposed fix
Renamed the xcframework to `CertificateSDKPackage.xcframework` and adjust the `path` parameter of the `Package.swift`.

An alternative would be to rename the package completely and keep the name of the xcframework. This however might cause conflicts with projects that use the framework.

## Reference
There is no real public documentation for this change, only one other thread [here](https://support.zendesk.com/hc/en-us/community/posts/4429572484762-Xcode-13-3-Beta-3-artifact-not-found-for-target).

I was able to verify that fix solves the issue on Xcode 13.3 RC.

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -14,7 +14,7 @@ let package = Package(
     targets: [
         .binaryTarget(
             name: "CertificateSDKPackage",
-            path: "CertificateSDK.xcframework"
+            path: "CertificateSDKPackage.xcframework"
```
Comment (macblazer) [inline Package.swift]: Instead of renaming the .xcframework file, let's just modify the `Package.swift` file internal target names.  So line 16 becomes `name: "CertificateSDK"` and line 12 becomes `targets: ["CertificateSDK"]`.

It's a simple two line change in one file, and we don't end up with "...Package" on the framework name.

**Review by macblazer — CHANGES_REQUESTED** [review]
Thanks for the PR for this, but there's a simpler fix that is a little better in the long run.  If you want to remove the rename of the .xcframework file, then modify the two lines in the Package.swift we can accept this contribution.

Projects using the .xcframework directly (not through Swift Package Manager) are not impacted by a simple two line change to the `Package.swift` file.

File: Package.swift (hunk 1 above)
Comment (PinkidG) [reply Package.swift]: Done 👍

**Comment by PinkidG** [comment]
As requested, I simply removed the `Package` suffix everywhere, seems to work just as well. 🙂

**Review by macblazer — APPROVED** [review]
Looks great.
